spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

loggint:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace